name: Continuous integration of wheels on armv6l
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dist
      run: |
        mkdir -p dist
      shell: bash
    - uses: pguyot/arm-runner-action@v1
      with:
        image_additional_mb: 1024
        commands: |
            apt-get update -y
            apt-get install --no-install-recommends -y python3 python3-pip python3-dev python3-venv python3-setuptools
            python3 -m venv venv
            venv/bin/pip install --upgrade pip
            venv/bin/pip install wheel
            venv/bin/pip install https://github.com/pguyot/snips-nlu-utils/releases/download/v0.9.1/snips_nlu_utils-0.9.1-cp37-cp37m-linux_armv6l.whl
            venv/bin/pip install https://github.com/pguyot/snips-nlu-parsers/releases/download/v0.4.3/snips_nlu_parsers-0.4.3-cp37-cp37m-linux_armv6l.whl
            venv/bin/pip install numpy==1.20.2 scikit-learn==0.22.2.post1 scipy==1.6.2
            venv/bin/python setup.py bdist_wheel
        copy_artifact_path:
            dist/*.whl
        copy_artifact_dest:
            dist
    - name: Archive target wheel
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: |
            dist/*.whl
